### ISSUE TITLE
AccountContextService는 사용하지 않으시는건가요??

### ISSUE THREAD

**Issue by pci2676** [seulgiwendy/spring-jwt#2]
동영상 보면서 Spring Security 공부중인데
AccountContextSerive를 사용하는 부분을 보지 못했습니다.
Provider에서 사용하시려다가 결국 사용 안하시던데

AccountContext만 사용하여 인증을 처리하여도 무관한건가요?

제가 스프링을 공부한지 얼마 되지 않아 이렇게 하는게 올바른지는 잘 모르겠지만 만약 AccountContextService를 Provider에서 사용한다면 첨부한 사진과

 같이 사용해도 되는 것인가요?

![캡처](https://user-images.githubusercontent.com/13347548/56868592-572bb480-6a2f-11e9-9d7e-3065dd0e8a5b.JPG)

**Comment by wheejuni** [comment]
@pci2676 안녕하세요. 확인이 늦었네요. ㅜㅜㅜ

제가 구현한 Provider는 이미 인증이 완료되어 header에 토큰을 갖고 있는 경우에만 인증을 처리하게끔 구현한 것이기때문에, (제 동영상을 시청해 주셨다면 이미 알고 계시겠지만) JWT의 payload가 들고 있는 정보만 가지고도 유저를 식별하고 권한을 인가하는 것이 가능했습니다. 

그런데 지금 구현하신 프로바이더를 보면 AJAX 기반으로 ID/PW 로그인 처리를 시도하시려는 것으로 보입니다. 

이 경우에는 지금 구현하신 대로 계정 정보를 조회하는 컴포넌트를 주입받아 사용하시는 것도 무방합니다. ^^

다만 AJAX 콜이 발생할 때마다 DB를 조회하는데 따르는 부하 이슈와... 응답이 지연될 수 있는 잠재적인 리스크(?) 는 충분히 고려해 보셔야 할 것으로 생각됩니다. 

개인적인 판단이지만 AJAX 콜을 위해서라면 세션 기반 인증을 사용하신 후에 세션에 담겨있는 인증 정보를 통해 사용자를 인증하는 것이 더 나은 방향이 아닐지... 생각해 봅니다~ 

부족한 영상과 자료에 관심 가져주셔서 감사합니다~ ^3^

**Comment by pci2676** [comment]
제가 공부가 아직 미흡해서 완벽히 이해하지는 못하지만 
그래도 동영상 보고 시큐리티에 대해서 많은 공부를 했습니다!
댓글 달아주셔서 감사합니다!
